# Generated by Django 3.1.7 on 2021-04-02 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
    ]
