# Generated by Django 3.1.7 on 2021-03-16 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_formmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formmodel',
            name='address',
        ),
        migrations.RemoveField(
            model_name='formmodel',
            name='age',
        ),
        migrations.AddField(
            model_name='formmodel',
            name='description',
            field=models.TextField(default='brief description of product', max_length=140, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Product price'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='name',
            field=models.CharField(max_length=80, verbose_name='Product Name'),
        ),
    ]
