# Generated by Django 3.1.7 on 2021-03-16 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210316_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formmodel',
            name='description',
            field=models.TextField(max_length=140, verbose_name='brief description of product'),
        ),
    ]
