# Generated by Django 3.1.7 on 2021-03-16 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210316_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='formmodel',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
