# Generated by Django 3.1.7 on 2021-03-16 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_formmodel_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formmodel',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Product image'),
        ),
    ]
