# Generated by Django 3.1.7 on 2021-03-17 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210317_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='formmodel',
            name='category',
            field=models.IntegerField(choices=[(1, 'Crafts'), (2, 'Home and Living'), (3, 'Jewellery'), (4, 'Accessories'), (5, 'Art')], default=1, verbose_name='Choose product category'),
        ),
    ]
