# Generated by Django 3.1.7 on 2021-03-17 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('main', '0009_sellers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sellers',
        ),
    ]
